{% macro state_name_to_abbreviation(state) %}

    CASE 
        WHEN TRIM(UPPER({{ state }})) = 'ALABAMA' THEN 'AL'
        WHEN TRIM(UPPER({{ state }})) = 'ALASKA' THEN 'AK'
        WHEN TRIM(UPPER({{ state }})) = 'ARIZONA' THEN 'AZ'
        WHEN TRIM(UPPER({{ state }})) = 'ARKANSAS' THEN 'AR'
        WHEN TRIM(UPPER({{ state }})) = 'CALIFORNIA' THEN 'CA'
        WHEN TRIM(UPPER({{ state }})) = 'COLORADO' THEN 'CO'
        WHEN TRIM(UPPER({{ state }})) = 'CONNECTICUT' THEN 'CT'
        WHEN TRIM(UPPER({{ state }})) = 'DELAWARE' THEN 'DE'
        WHEN TRIM(UPPER({{ state }})) = 'FLORIDA' THEN 'FL'
        WHEN TRIM(UPPER({{ state }})) = 'GEORGIA' THEN 'GA'
        WHEN TRIM(UPPER({{ state }})) = 'HAWAII' THEN 'HI'
        WHEN TRIM(UPPER({{ state }})) = 'IDAHO' THEN 'ID'
        WHEN TRIM(UPPER({{ state }})) = 'ILLINOIS' THEN 'IL'
        WHEN TRIM(UPPER({{ state }})) = 'INDIANA' THEN 'IN'
        WHEN TRIM(UPPER({{ state }})) = 'IOWA' THEN 'IA'
        WHEN TRIM(UPPER({{ state }})) = 'KANSAS' THEN 'KS'
        WHEN TRIM(UPPER({{ state }})) = 'KENTUCKY' THEN 'KY'
        WHEN TRIM(UPPER({{ state }})) = 'LOUISIANA' THEN 'LA'
        WHEN TRIM(UPPER({{ state }})) = 'MAINE' THEN 'ME'
        WHEN TRIM(UPPER({{ state }})) = 'MARYLAND' THEN 'MD'
        WHEN TRIM(UPPER({{ state }})) = 'MASSACHUSETTS' THEN 'MA'
        WHEN TRIM(UPPER({{ state }})) = 'MICHIGAN' THEN 'MI'
        WHEN TRIM(UPPER({{ state }})) = 'MINNESOTA' THEN 'MN'
        WHEN TRIM(UPPER({{ state }})) = 'MISSISSIPPI' THEN 'MS'
        WHEN TRIM(UPPER({{ state }})) = 'MISSOURI' THEN 'MO'
        WHEN TRIM(UPPER({{ state }})) = 'MONTANA' THEN 'MT'
        WHEN TRIM(UPPER({{ state }})) = 'NEBRASKA' THEN 'NE'
        WHEN TRIM(UPPER({{ state }})) = 'NEVADA' THEN 'NV'
        WHEN TRIM(UPPER({{ state }})) = 'NEW HAMPSHIRE' THEN 'NH'
        WHEN TRIM(UPPER({{ state }})) = 'NEW JERSEY' THEN 'NJ'
        WHEN TRIM(UPPER({{ state }})) = 'NEW MEXICO' THEN 'NM'
        WHEN TRIM(UPPER({{ state }})) = 'NEW YORK' THEN 'NY'
        WHEN TRIM(UPPER({{ state }})) = 'NORTH CAROLINA' THEN 'NC'
        WHEN TRIM(UPPER({{ state }})) = 'NORTH DAKOTA' THEN 'ND'
        WHEN TRIM(UPPER({{ state }})) = 'OHIO' THEN 'OH'
        WHEN TRIM(UPPER({{ state }})) = 'OKLAHOMA' THEN 'OK'
        WHEN TRIM(UPPER({{ state }})) = 'OREGON' THEN 'OR'
        WHEN TRIM(UPPER({{ state }})) = 'PENNSYLVANIA' THEN 'PA'
        WHEN TRIM(UPPER({{ state }})) = 'RHODE ISLAND' THEN 'RI'
        WHEN TRIM(UPPER({{ state }})) = 'SOUTH CAROLINA' THEN 'SC'
        WHEN TRIM(UPPER({{ state }})) = 'SOUTH DAKOTA' THEN 'SD'
        WHEN TRIM(UPPER({{ state }})) = 'TENNESSEE' THEN 'TN'
        WHEN TRIM(UPPER({{ state }})) = 'TEXAS' THEN 'TX'
        WHEN TRIM(UPPER({{ state }})) = 'UTAH' THEN 'UT'
        WHEN TRIM(UPPER({{ state }})) = 'VERMONT' THEN 'VT'
        WHEN TRIM(UPPER({{ state }})) = 'VIRGINIA' THEN 'VA'
        WHEN TRIM(UPPER({{ state }})) = 'WASHINGTON' THEN 'WA'
        WHEN TRIM(UPPER({{ state }})) = 'WEST VIRGINIA' THEN 'WV'
        WHEN TRIM(UPPER({{ state }})) = 'WISCONSIN' THEN 'WI'
        WHEN TRIM(UPPER({{ state }})) = 'WYOMING' THEN 'WY'
        ELSE TRIM(UPPER({{ state }})) 
        END

{% endmacro %}